spring:
  datasource:
    url: jdbc:mysql://49.235.239.71:3306/mytrain
    username: admin
    password: j4xRG.mod53F
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 81
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 1s
  servlet:
    context-path: /