spring:
  datasource:
    url: jdbc:mysql://49.235.239.71:3306/mytrain
    username: admin
    password: j4xRG.mod53F
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      connectionTimeout: 6000
      soTimeout: 6000
      maxAttempts: 5
      password:

server:
  port: 81
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 1s
  servlet:
    context-path: /